project_id = "promoes"
cluster_name = "gke-cluster-1"
region = "us-central1"
zone = "us-central1-c"
network = "gke-network-1"
subnetwork = "gke-subnet-1"
ip_range_pods_name = "gke-pod-range-1"
ip_range_services_name = "gke-service-range-1"
